
const LANGS = {
    "C#": [10, "text/x-csharp"],
    "C/C++": [7, "text/x-c++src"],
    "Clojure": [2, "text/x-clojure"],
    "Java": [8, "text/x-java"],
    "Go": [6, "text/x-go"],
    "Plain JavaScript": [4, "text/javascript"],
    "PHP": [3, "text/x-php"],
    "Python": [0, "text/x-python"],
    "Ruby": [1, "text/x-ruby"],
    "Scala": [5, "text/x-scala"],
    "VB.NET": [9, "text/x-vb"],
    "Bash": [11, "text/x-bash"],
    "Objective-C": [12,"text/x-objectivec"],
    "MySQL": [13,"text/x-sql"],
    "Perl": [14, "text/x-perl"],
    "Rust": [15, "text/rust"],
    "Swift": [16, "text/swift"],
    "R": [17, "text/r"],
    "Python3": [18, "text/x-python3"],
    "Ada": [19, "text/x-adasrc"],
    "Algol": [20, "text/x-algol"],
    "Cobol": [21, "text/x-cobol"],
    "Coffeescript": [22, "application/vnd.coffeescript"],
    "Commonlisp": [23, "text/x-lisp"],
    "D": [24, "text/x-dlang"],
    "Elixir": [25, "text/x-elixir"],
    "Erlang": [26, "text/x-erlang"],
    "F#": [27, "text/x-fsharp"],
    "Fortran": [28, "text/x-fortran"],
    "Groovy": [29, "text/x-groovy"],
    "Hack": [30, "text/x-hack"],
    "Haskell": [31, "text/x-haskell"],
    "Julia": [32, "text/x-julia"],
    "Kotlin": [33, "text/x-kotlin"],
    "Logo": [34, "text/x-logo"],
    "Lua": [35, "text/x-lua"],
    "Luna": [36, "text/x-luna"],
    "Ocaml": [37, "text/x-ocaml"],
    "Octave": [38, "text/x-octave"],
    "Opal": [39, "text/x-opal"],
    "Pascal": [40, "text/x-pascal"],
    "Prolog": [41, "text/x-prolog"],
    "Racket": [42, "text/x-racket"],
    "Smalltalk": [43, "text/x-smalltalk"],
    "Tcl": [44, "text/x-tcl"],
};

const Codes = {
    "Perl" : "use strict;\nuse warnings\n;use v5.14; say 'Hello';",
    "MySQL":"create table myTable(name varchar(10));\ninsert into myTable values(\"Hello\");\nselect * from myTable;",
    "Java": "/* package whatever; // don't place package name! */\n\nimport java.io.*;\n\nclass myCode\n{\n\tpublic static void main (String[] args) throws java.lang.Exception\n\t{\n\t\t\n\t\tSystem.out.println(\"Hello\");\n\t}\n}",
    "C/C++": "#include <iostream>\nusing namespace std;\n\nint main() {\n\tcout<<\"Hello\";\n\treturn 0;\n}",
    "C#": "using System;\n\npublic class Test\n{\n\tpublic static void Main()\n\t{\n\t\t\tConsole.WriteLine(\"Hello\");\n\t}\n}",
    "Clojure": '(println "Hello")',
    "Go": "package main\nimport \"fmt\"\n\nfunc main(){\n  \n\tfmt.Printf(\"Hello\")\n}",
    "Plain JavaScript": "//Not happy with Plain JS? Use JS/HTML/CSS option for using your own libraries.\n\nconsole.log(\"Hello\");",
    "PHP": "<?php\n$ho = fopen('php://stdout', \"w\");\n\nfwrite($ho, \"Hello\");\n\n\nfclose($ho);\n",
    "Python": "print \"Hello\"",
    "Python3": "print \"Hello\"",
    "Ruby": "puts \"Hello\"",
    "Bash": "echo 'Hi' ",
    "Objective-C": "#include <Foundation/Foundation.h>\n\n@interface Test\n+ (const char *) classStringValue;\n@end\n\n@implementation Test\n+ (const char *) classStringValue;\n{\n    return \"Hey!\";\n}\n@end\n\nint main(void)\n{\n    printf(\"%s\\n\", [Test classStringValue]);\n    return 0;\n}",
    "Scala": "object HelloWorld {def main(args: Array[String]) = println(\"Hello\")}",
    "VB.NET": "Imports System\n\nPublic Class Test\n\tPublic Shared Sub Main() \n    \tSystem.Console.WriteLine(\"Hello\")\n\tEnd Sub\nEnd Class",
    "Rust": "fn main() {\n\tprintln!(\"Hello\");\n}",
    "Swift": "print(\"Hello, world!\")",
    "R": "print(\"Hello World, from R!\")",
    "Ada": "",
    "Algol": "",
    "Cobol": "",
    "Coffeescript": "",
    "Commonlisp": "",
    "D": "",
    "Elixir": "",
    "Erlang": "",
    "F#": "",
    "Fortran": "",
    "Groovy": "",
    "Hack": "",
    "Haskell": "",
    "Julia": "",
    "Kotlin": "",
    "Logo": "",
    "Lua": "",
    "Luna": "",
    "Ocaml": "",
    "Octave": "",
    "Opal": "",
    "Pascal": "",
    "Prolog": "",
    "Racket": "",
    "Smalltalk": "",
    "Tcl": "",
};
